<a href="https://colab.research.google.com/github/ShathaMelhem/AI/blob/main/Pandas_Practical_Q.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Creat Data

In [53]:
data = {
    'Name': ['Lina', 'Omar', 'Sami', 'Sara','Rami' ,'Tariq','Mona','Zain','Leena','Ahmed'],
    'Age':[25.0,30.0,None,22.0,35.0,40.0,25.0,33.0,28.0,30.0],
    'Gender':['Female','Male','Male','Female','Male','Male','Female','Male','Female','Male'],
    'Department':['IT','HR','Marketing','IT','Finance','HR','Marketing','IT','Finance','Marketing'],
    'Salary':[4500.0,5000.0,5200.0,48000.0,5600.0,6000.0,47000.0,5300.0,None,5100.0],
    'Experience':[3,5,2,1,6,7,4,5,3,4]
}

In [54]:
df=pd.DataFrame(data)

# Data Expolration

In [55]:
df.head()

   Name   Age  Gender Department   Salary  Experience
0  Lina  25.0  Female         IT   4500.0           3
1  Omar  30.0    Male         HR   5000.0           5
2  Sami   NaN    Male  Marketing   5200.0           2
3  Sara  22.0  Female         IT  48000.0           1
4  Rami  35.0    Male    Finance   5600.0           6

In [56]:
df.shape

(10, 6)

In [57]:
df.dtypes

Name           object
Age           float64
Gender         object
Department     object
Salary        float64
Experience      int64
dtype: object

In [58]:
df.columns

Index(['Name', 'Age', 'Gender', 'Department', 'Salary', 'Experience'], dtype='object')

In [8]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [9]:
print(df.isna().sum())
print('\nnumber of missing values is',df.isna().sum().sum())

Name          0
Age           1
Gender        0
Department    0
Salary        1
Experience    0
dtype: int64

number of missing values is 2

In [10]:
df.describe()

             Age        Salary  Experience
count   9.000000      9.000000   10.000000
mean   29.777778  14633.333333    4.000000
std     5.607535  18639.809548    1.825742
min    22.000000   4500.000000    1.000000
25%    25.000000   5100.000000    3.000000
50%    30.000000   5300.000000    4.000000
75%    33.000000   6000.000000    5.000000
max    40.000000  48000.000000    7.000000

In [11]:
df.describe(include=['object'])

        Name Gender Department
count     10     10         10
unique    10      2          4
top     Lina   Male         IT
freq       1      6          3

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Age         9 non-null      float64
 2   Gender      10 non-null     object
 3   Department  10 non-null     object
 4   Salary      9 non-null      float64
 5   Experience  10 non-null     int64
dtypes: float64(2), int64(1), object(3)
memory usage: 612.0+ bytes

# Selection and Indexing

In [59]:
df['Name']

0     Lina
1     Omar
2     Sami
3     Sara
4     Rami
5    Tariq
6     Mona
7     Zain
8    Leena
9    Ahmed
Name: Name, dtype: object

In [14]:
df[['Name','Salary']]

    Name   Salary
0   Lina   4500.0
1   Omar   5000.0
2   Sami   5200.0
3   Sara  48000.0
4   Rami   5600.0
5  Tariq   6000.0
6   Mona  47000.0
7   Zain   5300.0
8  Leena      NaN
9  Ahmed   5100.0

In [15]:
df.iloc[3]

Name             Sara
Age              22.0
Gender         Female
Department         IT
Salary        48000.0
Experience          1
Name: 3, dtype: object

In [16]:
df[df.loc[:,'Name']=='Lina']

   Name   Age  Gender Department  Salary  Experience
0  Lina  25.0  Female         IT  4500.0           3

In [17]:
df.loc[df['Name']=='Omar','Salary']=4700
df

    Name   Age  Gender Department   Salary  Experience
0   Lina  25.0  Female         IT   4500.0           3
1   Omar  30.0    Male         HR   4700.0           5
2   Sami   NaN    Male  Marketing   5200.0           2
3   Sara  22.0  Female         IT  48000.0           1
4   Rami  35.0    Male    Finance   5600.0           6
5  Tariq  40.0    Male         HR   6000.0           7
6   Mona  25.0  Female  Marketing  47000.0           4
7   Zain  33.0    Male         IT   5300.0           5
8  Leena  28.0  Female    Finance      NaN           3
9  Ahmed  30.0    Male  Marketing   5100.0           4

In [18]:
df.loc[df['Department']=='IT']

   Name   Age  Gender Department   Salary  Experience
0  Lina  25.0  Female         IT   4500.0           3
3  Sara  22.0  Female         IT  48000.0           1
7  Zain  33.0    Male         IT   5300.0           5

In [19]:
df.loc[df['Age']>26]

    Name   Age  Gender Department  Salary  Experience
1   Omar  30.0    Male         HR  4700.0           5
4   Rami  35.0    Male    Finance  5600.0           6
5  Tariq  40.0    Male         HR  6000.0           7
7   Zain  33.0    Male         IT  5300.0           5
8  Leena  28.0  Female    Finance     NaN           3
9  Ahmed  30.0    Male  Marketing  5100.0           4

In [20]:
df[df['Gender'] == 'Female']['Salary']

0     4500.0
3    48000.0
6    47000.0
8        NaN
Name: Salary, dtype: float64

In [21]:
df[df['Experience']<3]

   Name   Age  Gender Department   Salary  Experience
2  Sami   NaN    Male  Marketing   5200.0           2
3  Sara  22.0  Female         IT  48000.0           1

In [22]:
df[df['Department']=='HR']['Age']

1    30.0
5    40.0
Name: Age, dtype: float64

# Conditional Filtering

In [23]:
df.query('Age>30')

    Name   Age Gender Department  Salary  Experience
4   Rami  35.0   Male    Finance  5600.0           6
5  Tariq  40.0   Male         HR  6000.0           7
7   Zain  33.0   Male         IT  5300.0           5

In [24]:
df.query('Department=="Marketing"')

    Name   Age  Gender Department   Salary  Experience
2   Sami   NaN    Male  Marketing   5200.0           2
6   Mona  25.0  Female  Marketing  47000.0           4
9  Ahmed  30.0    Male  Marketing   5100.0           4

In [25]:
df.query('Gender=="Female" and Department=="IT"')

   Name   Age  Gender Department   Salary  Experience
0  Lina  25.0  Female         IT   4500.0           3
3  Sara  22.0  Female         IT  48000.0           1

In [26]:
df.query('Salary>=5000 and Salary<=6000')

    Name   Age Gender Department  Salary  Experience
2   Sami   NaN   Male  Marketing  5200.0           2
4   Rami  35.0   Male    Finance  5600.0           6
5  Tariq  40.0   Male         HR  6000.0           7
7   Zain  33.0   Male         IT  5300.0           5
9  Ahmed  30.0   Male  Marketing  5100.0           4

In [27]:
df.query('Experience>=2 and Experience<=5')

    Name   Age  Gender Department   Salary  Experience
0   Lina  25.0  Female         IT   4500.0           3
1   Omar  30.0    Male         HR   4700.0           5
2   Sami   NaN    Male  Marketing   5200.0           2
6   Mona  25.0  Female  Marketing  47000.0           4
7   Zain  33.0    Male         IT   5300.0           5
8  Leena  28.0  Female    Finance      NaN           3
9  Ahmed  30.0    Male  Marketing   5100.0           4

In [28]:
df[df['Age'].isna()]

   Name  Age Gender Department  Salary  Experience
2  Sami  NaN   Male  Marketing  5200.0           2

In [29]:
df[df['Experience'].isna()]

Empty DataFrame
Columns: [Name, Age, Gender, Department, Salary, Experience]
Index: []

In [30]:
df.query('Department!="IT"')

    Name   Age  Gender Department   Salary  Experience
1   Omar  30.0    Male         HR   4700.0           5
2   Sami   NaN    Male  Marketing   5200.0           2
4   Rami  35.0    Male    Finance   5600.0           6
5  Tariq  40.0    Male         HR   6000.0           7
6   Mona  25.0  Female  Marketing  47000.0           4
8  Leena  28.0  Female    Finance      NaN           3
9  Ahmed  30.0    Male  Marketing   5100.0           4

In [31]:
df.query('Name.str.startswith("S")')

   Name   Age  Gender Department   Salary  Experience
2  Sami   NaN    Male  Marketing   5200.0           2
3  Sara  22.0  Female         IT  48000.0           1

In [32]:
df.query('Name.str.contains("a")')

    Name   Age  Gender Department   Salary  Experience
0   Lina  25.0  Female         IT   4500.0           3
1   Omar  30.0    Male         HR   4700.0           5
2   Sami   NaN    Male  Marketing   5200.0           2
3   Sara  22.0  Female         IT  48000.0           1
4   Rami  35.0    Male    Finance   5600.0           6
5  Tariq  40.0    Male         HR   6000.0           7
6   Mona  25.0  Female  Marketing  47000.0           4
7   Zain  33.0    Male         IT   5300.0           5
8  Leena  28.0  Female    Finance      NaN           3

# Data Modification and Creation

In [61]:
df['Bonus']=df['Salary']*0.1
df

    Name   Age  Gender Department   Salary  Experience   Bonus
0   Lina  25.0  Female         IT   4500.0           3   450.0
1   Omar  30.0    Male         HR   5000.0           5   500.0
2   Sami   NaN    Male  Marketing   5200.0           2   520.0
3   Sara  22.0  Female         IT  48000.0           1  4800.0
4   Rami  35.0    Male    Finance   5600.0           6   560.0
5  Tariq  40.0    Male         HR   6000.0           7   600.0
6   Mona  25.0  Female  Marketing  47000.0           4  4700.0
7   Zain  33.0    Male         IT   5300.0           5   530.0
8  Leena  28.0  Female    Finance      NaN           3     NaN
9  Ahmed  30.0    Male  Marketing   5100.0           4   510.0

In [62]:
df['Net Salary']=df['Salary']+df['Bonus']
df

    Name   Age  Gender Department   Salary  Experience   Bonus  Net Salary
0   Lina  25.0  Female         IT   4500.0           3   450.0      4950.0
1   Omar  30.0    Male         HR   5000.0           5   500.0      5500.0
2   Sami   NaN    Male  Marketing   5200.0           2   520.0      5720.0
3   Sara  22.0  Female         IT  48000.0           1  4800.0     52800.0
4   Rami  35.0    Male    Finance   5600.0           6   560.0      6160.0
5  Tariq  40.0    Male         HR   6000.0           7   600.0      6600.0
6   Mona  25.0  Female  Marketing  47000.0           4  4700.0     51700.0
7   Zain  33.0    Male         IT   5300.0           5   530.0      5830.0
8  Leena  28.0  Female    Finance      NaN           3     NaN         NaN
9  Ahmed  30.0    Male  Marketing   5100.0           4   510.0      5610.0

In [63]:
df['Age Group']=df['Age'].apply(lambda x: 'Young' if x<30 else 'Old')
df

,Name,Age,Gender,Department,Salary,Experience,Bonus,Net Salary,Age Group
0,Lina,25.0,Female,IT,4500.0,3,450.0,4950.0,Young
1,Omar,30.0,Male,HR,5000.0,5,500.0,5500.0,Old
2,Sami,NaN,Male,Marketing,5200.0,2,520.0,5720.0,Old
3,Sara,22.0,Female,IT,48000.0,1,4800.0,52800.0,Young
4,Rami,35.0,Male,Finance,5600.0,6,560.0,6160.0,Old
5,Tariq,40.0,Male,HR,6000.0,7,600.0,6600.0,Old
6,Mona,25.0,Female,Marketing,47000.0,4,4700.0,51700.0,Young
7,Zain,33.0,Male,IT,5300.0,5,530.0,5830.0,Old
8,Leena,28.0,Female,Finance,NaN,3,NaN,NaN,Young
9,Ahmed,30.0,Male,Marketing,5100.0,4,510.0,5610.0,Old

In [64]:
df.columns=df.columns.str.lower()
df

,name,age,gender,department,salary,experience,bonus,net salary,age group
0,Lina,25.0,Female,IT,4500.0,3,450.0,4950.0,Young
1,Omar,30.0,Male,HR,5000.0,5,500.0,5500.0,Old
2,Sami,NaN,Male,Marketing,5200.0,2,520.0,5720.0,Old
3,Sara,22.0,Female,IT,48000.0,1,4800.0,52800.0,Young
4,Rami,35.0,Male,Finance,5600.0,6,560.0,6160.0,Old
5,Tariq,40.0,Male,HR,6000.0,7,600.0,6600.0,Old
6,Mona,25.0,Female,Marketing,47000.0,4,4700.0,51700.0,Young
7,Zain,33.0,Male,IT,5300.0,5,530.0,5830.0,Old
8,Leena,28.0,Female,Finance,NaN,3,NaN,NaN,Young
9,Ahmed,30.0,Male,Marketing,5100.0,4,510.0,5610.0,Old

In [65]:
df.rename(columns={'salary':'Base Salary'},inplace=True)
df

,name,age,gender,department,Base Salary,experience,bonus,net salary,age group
0,Lina,25.0,Female,IT,4500.0,3,450.0,4950.0,Young
1,Omar,30.0,Male,HR,5000.0,5,500.0,5500.0,Old
2,Sami,NaN,Male,Marketing,5200.0,2,520.0,5720.0,Old
3,Sara,22.0,Female,IT,48000.0,1,4800.0,52800.0,Young
4,Rami,35.0,Male,Finance,5600.0,6,560.0,6160.0,Old
5,Tariq,40.0,Male,HR,6000.0,7,600.0,6600.0,Old
6,Mona,25.0,Female,Marketing,47000.0,4,4700.0,51700.0,Young
7,Zain,33.0,Male,IT,5300.0,5,530.0,5830.0,Old
8,Leena,28.0,Female,Finance,NaN,3,NaN,NaN,Young
9,Ahmed,30.0,Male,Marketing,5100.0,4,510.0,5610.0,Old

In [66]:
#delete column
df.drop('net salary',axis=1,inplace=True)
df

    name   age  gender department  Base Salary  experience   bonus age group
0   Lina  25.0  Female         IT       4500.0           3   450.0     Young
1   Omar  30.0    Male         HR       5000.0           5   500.0       Old
2   Sami   NaN    Male  Marketing       5200.0           2   520.0       Old
3   Sara  22.0  Female         IT      48000.0           1  4800.0     Young
4   Rami  35.0    Male    Finance       5600.0           6   560.0       Old
5  Tariq  40.0    Male         HR       6000.0           7   600.0       Old
6   Mona  25.0  Female  Marketing      47000.0           4  4700.0     Young
7   Zain  33.0    Male         IT       5300.0           5   530.0       Old
8  Leena  28.0  Female    Finance          NaN           3     NaN     Young
9  Ahmed  30.0    Male  Marketing       5100.0           4   510.0       Old

In [67]:
df.drop(df.index[-1],inplace=True)
df

    name   age  gender department  Base Salary  experience   bonus age group
0   Lina  25.0  Female         IT       4500.0           3   450.0     Young
1   Omar  30.0    Male         HR       5000.0           5   500.0       Old
2   Sami   NaN    Male  Marketing       5200.0           2   520.0       Old
3   Sara  22.0  Female         IT      48000.0           1  4800.0     Young
4   Rami  35.0    Male    Finance       5600.0           6   560.0       Old
5  Tariq  40.0    Male         HR       6000.0           7   600.0       Old
6   Mona  25.0  Female  Marketing      47000.0           4  4700.0     Young
7   Zain  33.0    Male         IT       5300.0           5   530.0       Old
8  Leena  28.0  Female    Finance          NaN           3     NaN     Young

In [68]:
df.reindex(columns=['name','age','gender','department','Base Salary','bonus','experience','age group'])

    name   age  gender department  Base Salary   bonus  experience age group
0   Lina  25.0  Female         IT       4500.0   450.0           3     Young
1   Omar  30.0    Male         HR       5000.0   500.0           5       Old
2   Sami   NaN    Male  Marketing       5200.0   520.0           2       Old
3   Sara  22.0  Female         IT      48000.0  4800.0           1     Young
4   Rami  35.0    Male    Finance       5600.0   560.0           6       Old
5  Tariq  40.0    Male         HR       6000.0   600.0           7       Old
6   Mona  25.0  Female  Marketing      47000.0  4700.0           4     Young
7   Zain  33.0    Male         IT       5300.0   530.0           5       Old
8  Leena  28.0  Female    Finance          NaN     NaN           3     Young

In [69]:
#add new row to df
new_row=['Newname',45.0,'Male','IT',3000.0,100.0,1,'Old']
df=pd.concat([df,pd.DataFrame([new_row],columns=df.columns)],ignore_index=True)

df

      name   age  gender department  Base Salary  experience   bonus age group
0     Lina  25.0  Female         IT       4500.0         3.0   450.0     Young
1     Omar  30.0    Male         HR       5000.0         5.0   500.0       Old
2     Sami   NaN    Male  Marketing       5200.0         2.0   520.0       Old
3     Sara  22.0  Female         IT      48000.0         1.0  4800.0     Young
4     Rami  35.0    Male    Finance       5600.0         6.0   560.0       Old
5    Tariq  40.0    Male         HR       6000.0         7.0   600.0       Old
6     Mona  25.0  Female  Marketing      47000.0         4.0  4700.0     Young
7     Zain  33.0    Male         IT       5300.0         5.0   530.0       Old
8    Leena  28.0  Female    Finance          NaN         3.0     NaN     Young
9  Newname  45.0    Male         IT       3000.0       100.0     1.0       Old

In [70]:
df['length']=df['name'].str.len()
df

,name,age,gender,department,Base Salary,experience,bonus,age group,length
0,Lina,25.0,Female,IT,4500.0,3.0,450.0,Young,4
1,Omar,30.0,Male,HR,5000.0,5.0,500.0,Old,4
2,Sami,NaN,Male,Marketing,5200.0,2.0,520.0,Old,4
3,Sara,22.0,Female,IT,48000.0,1.0,4800.0,Young,4
4,Rami,35.0,Male,Finance,5600.0,6.0,560.0,Old,4
5,Tariq,40.0,Male,HR,6000.0,7.0,600.0,Old,5
6,Mona,25.0,Female,Marketing,47000.0,4.0,4700.0,Young,4
7,Zain,33.0,Male,IT,5300.0,5.0,530.0,Old,4
8,Leena,28.0,Female,Finance,NaN,3.0,NaN,Young,5
9,Newname,45.0,Male,IT,3000.0,100.0,1.0,Old,7

# Sorting and Grouping

In [74]:
df.sort_values(by='Base Salary',ascending=True)

,name,age,gender,department,Base Salary,experience,bonus,age group,length
9,Newname,45.0,Male,IT,3000.0,100.0,1.0,Old,7
0,Lina,25.0,Female,IT,4500.0,3.0,450.0,Young,4
1,Omar,30.0,Male,HR,5000.0,5.0,500.0,Old,4
2,Sami,NaN,Male,Marketing,5200.0,2.0,520.0,Old,4
7,Zain,33.0,Male,IT,5300.0,5.0,530.0,Old,4
4,Rami,35.0,Male,Finance,5600.0,6.0,560.0,Old,4
5,Tariq,40.0,Male,HR,6000.0,7.0,600.0,Old,5
6,Mona,25.0,Female,Marketing,47000.0,4.0,4700.0,Young,4
3,Sara,22.0,Female,IT,48000.0,1.0,4800.0,Young,4
8,Leena,28.0,Female,Finance,NaN,3.0,NaN,Young,5

In [75]:
df.sort_values(by='age',ascending=False)

,name,age,gender,department,Base Salary,experience,bonus,age group,length
9,Newname,45.0,Male,IT,3000.0,100.0,1.0,Old,7
5,Tariq,40.0,Male,HR,6000.0,7.0,600.0,Old,5
4,Rami,35.0,Male,Finance,5600.0,6.0,560.0,Old,4
7,Zain,33.0,Male,IT,5300.0,5.0,530.0,Old,4
1,Omar,30.0,Male,HR,5000.0,5.0,500.0,Old,4
8,Leena,28.0,Female,Finance,NaN,3.0,NaN,Young,5
0,Lina,25.0,Female,IT,4500.0,3.0,450.0,Young,4
6,Mona,25.0,Female,Marketing,47000.0,4.0,4700.0,Young,4
3,Sara,22.0,Female,IT,48000.0,1.0,4800.0,Young,4
2,Sami,NaN,Male,Marketing,5200.0,2.0,520.0,Old,4

In [76]:
result=df.groupby('department')['Base Salary'].mean()
result

department
Finance       5600.0
HR            5500.0
IT           15200.0
Marketing    26100.0
Name: Base Salary, dtype: float64

In [78]:
result=df.groupby('department')['name'].count()
result

department
Finance      2
HR           2
IT           4
Marketing    2
Name: name, dtype: int64

In [80]:
result=df.groupby('department')['Base Salary'].max()
result

department
Finance       5600.0
HR            6000.0
IT           48000.0
Marketing    47000.0
Name: Base Salary, dtype: float64

In [81]:
result=df.groupby('gender')['experience'].mean()
result

gender
Female     2.750000
Male      20.833333
Name: experience, dtype: float64

In [82]:
#pivot_table to get average salary by gender and department
result=df.pivot_table(index='department',columns='gender',values='Base Salary',aggfunc='mean')
result

gender       Female    Male
department
Finance         NaN  5600.0
HR              NaN  5500.0
IT          26250.0  4150.0
Marketing   47000.0  5200.0

In [84]:
result=df.groupby('department')['gender'].value_counts()
result

department  gender
Finance     Female    1
            Male      1
HR          Male      2
IT          Female    2
            Male      2
Marketing   Female    1
            Male      1
Name: count, dtype: int64

In [85]:
result=df.groupby('age group')['Base Salary'].sum()
result

age group
Old      30100.0
Young    99500.0
Name: Base Salary, dtype: float64

In [99]:

result=df[(df['department'] == 'IT') & (df['experience'] > 3)].shape[0]  #.shape[0]: returns the number of matching rows

print(f'Number of employees have more than 3 years of experiance is: {result}')

Number of employees have more than 3 years of experiance is: 2

# Handling Missing Values

In [103]:
df_mean_age=df['age'].mean()
df['age'].fillna(df_mean_age)
df

,name,age,gender,department,Base Salary,experience,bonus,age group,length
0,Lina,25.0,Female,IT,4500.0,3.0,450.0,Young,4
1,Omar,30.0,Male,HR,5000.0,5.0,500.0,Old,4
2,Sami,NaN,Male,Marketing,5200.0,2.0,520.0,Old,4
3,Sara,22.0,Female,IT,48000.0,1.0,4800.0,Young,4
4,Rami,35.0,Male,Finance,5600.0,6.0,560.0,Old,4
5,Tariq,40.0,Male,HR,6000.0,7.0,600.0,Old,5
6,Mona,25.0,Female,Marketing,47000.0,4.0,4700.0,Young,4
7,Zain,33.0,Male,IT,5300.0,5.0,530.0,Old,4
8,Leena,28.0,Female,Finance,NaN,3.0,NaN,Young,5
9,Newname,45.0,Male,IT,3000.0,100.0,1.0,Old,7

In [104]:

df['gender'].fillna('Unknown')
df

,name,age,gender,department,Base Salary,experience,bonus,age group,length
0,Lina,25.0,Female,IT,4500.0,3.0,450.0,Young,4
1,Omar,30.0,Male,HR,5000.0,5.0,500.0,Old,4
2,Sami,NaN,Male,Marketing,5200.0,2.0,520.0,Old,4
3,Sara,22.0,Female,IT,48000.0,1.0,4800.0,Young,4
4,Rami,35.0,Male,Finance,5600.0,6.0,560.0,Old,4
5,Tariq,40.0,Male,HR,6000.0,7.0,600.0,Old,5
6,Mona,25.0,Female,Marketing,47000.0,4.0,4700.0,Young,4
7,Zain,33.0,Male,IT,5300.0,5.0,530.0,Old,4
8,Leena,28.0,Female,Finance,NaN,3.0,NaN,Young,5
9,Newname,45.0,Male,IT,3000.0,100.0,1.0,Old,7

In [105]:
df.dropna()

,name,age,gender,department,Base Salary,experience,bonus,age group,length
0,Lina,25.0,Female,IT,4500.0,3.0,450.0,Young,4
1,Omar,30.0,Male,HR,5000.0,5.0,500.0,Old,4
3,Sara,22.0,Female,IT,48000.0,1.0,4800.0,Young,4
4,Rami,35.0,Male,Finance,5600.0,6.0,560.0,Old,4
5,Tariq,40.0,Male,HR,6000.0,7.0,600.0,Old,5
6,Mona,25.0,Female,Marketing,47000.0,4.0,4700.0,Young,4
7,Zain,33.0,Male,IT,5300.0,5.0,530.0,Old,4
9,Newname,45.0,Male,IT,3000.0,100.0,1.0,Old,7

In [106]:
df.dropna(axis=1)

      name  gender department  experience age group  length
0     Lina  Female         IT         3.0     Young       4
1     Omar    Male         HR         5.0       Old       4
2     Sami    Male  Marketing         2.0       Old       4
3     Sara  Female         IT         1.0     Young       4
4     Rami    Male    Finance         6.0       Old       4
5    Tariq    Male         HR         7.0       Old       5
6     Mona  Female  Marketing         4.0     Young       4
7     Zain    Male         IT         5.0       Old       4
8    Leena  Female    Finance         3.0     Young       5
9  Newname    Male         IT       100.0       Old       7

In [108]:
df_clean=df.dropna()
df_clean

,name,age,gender,department,Base Salary,experience,bonus,age group,length
0,Lina,25.0,Female,IT,4500.0,3.0,450.0,Young,4
1,Omar,30.0,Male,HR,5000.0,5.0,500.0,Old,4
3,Sara,22.0,Female,IT,48000.0,1.0,4800.0,Young,4
4,Rami,35.0,Male,Finance,5600.0,6.0,560.0,Old,4
5,Tariq,40.0,Male,HR,6000.0,7.0,600.0,Old,5
6,Mona,25.0,Female,Marketing,47000.0,4.0,4700.0,Young,4
7,Zain,33.0,Male,IT,5300.0,5.0,530.0,Old,4
9,Newname,45.0,Male,IT,3000.0,100.0,1.0,Old,7

# Advanced Operations

In [109]:

df['squared age']=df['age'].apply(lambda x:x**2)
df

,name,age,gender,department,Base Salary,experience,bonus,age group,length,squared age
0,Lina,25.0,Female,IT,4500.0,3.0,450.0,Young,4,625.0
1,Omar,30.0,Male,HR,5000.0,5.0,500.0,Old,4,900.0
2,Sami,NaN,Male,Marketing,5200.0,2.0,520.0,Old,4,NaN
3,Sara,22.0,Female,IT,48000.0,1.0,4800.0,Young,4,484.0
4,Rami,35.0,Male,Finance,5600.0,6.0,560.0,Old,4,1225.0
5,Tariq,40.0,Male,HR,6000.0,7.0,600.0,Old,5,1600.0
6,Mona,25.0,Female,Marketing,47000.0,4.0,4700.0,Young,4,625.0
7,Zain,33.0,Male,IT,5300.0,5.0,530.0,Old,4,1089.0
8,Leena,28.0,Female,Finance,NaN,3.0,NaN,Young,5,784.0
9,Newname,45.0,Male,IT,3000.0,100.0,1.0,Old,7,2025.0

In [110]:
#replace
df['gender'].replace({'Male':1,'Female':0},inplace=True)
df

<ipython-input-110-3114760cd18b>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].replace({'Male':1,'Female':0},inplace=True)
<ipython-input-110-3114760cd18b>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gender'].replace({'Male':1,'Female':0},inplace=True)

,name,age,gender,department,Base Salary,experience,bonus,age group,length,squared age
0,Lina,25.0,0,IT,4500.0,3.0,450.0,Young,4,625.0
1,Omar,30.0,1,HR,5000.0,5.0,500.0,Old,4,900.0
2,Sami,NaN,1,Marketing,5200.0,2.0,520.0,Old,4,NaN
3,Sara,22.0,0,IT,48000.0,1.0,4800.0,Young,4,484.0
4,Rami,35.0,1,Finance,5600.0,6.0,560.0,Old,4,1225.0
5,Tariq,40.0,1,HR,6000.0,7.0,600.0,Old,5,1600.0
6,Mona,25.0,0,Marketing,47000.0,4.0,4700.0,Young,4,625.0
7,Zain,33.0,1,IT,5300.0,5.0,530.0,Old,4,1089.0
8,Leena,28.0,0,Finance,NaN,3.0,NaN,Young,5,784.0
9,Newname,45.0,1,IT,3000.0,100.0,1.0,Old,7,2025.0

In [111]:

def calculate_tax(salary):
    if salary>5000:
        return salary*0.05
    else:
        return 0
df['tax']=df['Base Salary'].apply(calculate_tax)
df

,name,age,gender,department,Base Salary,experience,bonus,age group,length,squared age,tax
0,Lina,25.0,0,IT,4500.0,3.0,450.0,Young,4,625.0,0.0
1,Omar,30.0,1,HR,5000.0,5.0,500.0,Old,4,900.0,0.0
2,Sami,NaN,1,Marketing,5200.0,2.0,520.0,Old,4,NaN,260.0
3,Sara,22.0,0,IT,48000.0,1.0,4800.0,Young,4,484.0,2400.0
4,Rami,35.0,1,Finance,5600.0,6.0,560.0,Old,4,1225.0,280.0
5,Tariq,40.0,1,HR,6000.0,7.0,600.0,Old,5,1600.0,300.0
6,Mona,25.0,0,Marketing,47000.0,4.0,4700.0,Young,4,625.0,2350.0
7,Zain,33.0,1,IT,5300.0,5.0,530.0,Old,4,1089.0,265.0
8,Leena,28.0,0,Finance,NaN,3.0,NaN,Young,5,784.0,0.0
9,Newname,45.0,1,IT,3000.0,100.0,1.0,Old,7,2025.0,0.0

In [112]:
salary_range=df['Base Salary'].max()-df['Base Salary'].min()
salary_range

45000.0

In [115]:
print('mean before removing outliers is ',df['Base Salary'].mean())
Q1=df['Base Salary'].quantile(0.25)
Q3=df['Base Salary'].quantile(0.75)
IQR=Q3-Q1
print('\nIQR is ',IQR)
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
print('\nlower bound is ',lower_bound)
print('\nupper bound is ',upper_bound)
df=df[(df['Base Salary']>=lower_bound) & (df['Base Salary']<=upper_bound)]
df

mean before removing outliers is  5266.666666666667

IQR is  475.0

lower bound is  4337.5

upper bound is  6237.5

,name,age,gender,department,Base Salary,experience,bonus,age group,length,squared age,tax
0,Lina,25.0,0,IT,4500.0,3.0,450.0,Young,4,625.0,0.0
1,Omar,30.0,1,HR,5000.0,5.0,500.0,Old,4,900.0,0.0
2,Sami,NaN,1,Marketing,5200.0,2.0,520.0,Old,4,NaN,260.0
4,Rami,35.0,1,Finance,5600.0,6.0,560.0,Old,4,1225.0,280.0
5,Tariq,40.0,1,HR,6000.0,7.0,600.0,Old,5,1600.0,300.0
7,Zain,33.0,1,IT,5300.0,5.0,530.0,Old,4,1089.0,265.0

# Reshaping Data

In [116]:
#pivot
pivot_df=df.pivot(index='name',columns='department',values='Base Salary')
pivot_df

department  Finance      HR      IT  Marketing
name
Lina            NaN     NaN  4500.0        NaN
Omar            NaN  5000.0     NaN        NaN
Rami         5600.0     NaN     NaN        NaN
Sami            NaN     NaN     NaN     5200.0
Tariq           NaN  6000.0     NaN        NaN
Zain            NaN     NaN  5300.0        NaN

In [117]:

pivot_table_df=df.pivot_table(index='department',columns='gender',values='Base Salary',aggfunc='mean')
pivot_table_df

gender           0       1
department
Finance        NaN  5600.0
HR             NaN  5500.0
IT          4500.0  5300.0
Marketing      NaN  5200.0

In [119]:
#melt for and and salary
melted_df=pd.melt(df,id_vars=['name'],value_vars=['Base Salary','age'],var_name='Attribute', value_name='Value')
melted_df

     name    Attribute   Value
0    Lina  Base Salary  4500.0
1    Omar  Base Salary  5000.0
2    Sami  Base Salary  5200.0
3    Rami  Base Salary  5600.0
4   Tariq  Base Salary  6000.0
5    Zain  Base Salary  5300.0
6    Lina          age    25.0
7    Omar          age    30.0
8    Sami          age     NaN
9    Rami          age    35.0
10  Tariq          age    40.0
11   Zain          age    33.0

In [120]:
stacked_df=df.stack()
stacked_df

0  name             Lina
   age              25.0
   gender              0
   department         IT
   Base Salary    4500.0
                   ...
7  bonus           530.0
   age group         Old
   length              4
   squared age    1089.0
   tax             265.0
Length: 64, dtype: object

In [128]:
grouped = df.groupby(['department', 'gender'])['Base Salary'].mean()
print(grouped)
print('\n______________________after unstack_______________________________')
unstacked = grouped.unstack()
print(unstacked)

department  gender
Finance     1         5600.0
HR          1         5500.0
IT          0         4500.0
            1         5300.0
Marketing   1         5200.0
Name: Base Salary, dtype: float64

______________________after unstack_______________________________
gender           0       1
department
Finance        NaN  5600.0
HR             NaN  5500.0
IT          4500.0  5300.0
Marketing      NaN  5200.0

In [129]:
df.T

                  0       1          2        4       5       7
name           Lina    Omar       Sami     Rami   Tariq    Zain
age            25.0    30.0        NaN     35.0    40.0    33.0
gender            0       1          1        1       1       1
department       IT      HR  Marketing  Finance      HR      IT
Base Salary  4500.0  5000.0     5200.0   5600.0  6000.0  5300.0
experience      3.0     5.0        2.0      6.0     7.0     5.0
bonus         450.0   500.0      520.0    560.0   600.0   530.0
age group     Young     Old        Old      Old     Old     Old
length            4       4          4        4       5       4
squared age   625.0   900.0        NaN   1225.0  1600.0  1089.0
tax             0.0     0.0      260.0    280.0   300.0   265.0

In [130]:
df

,name,age,gender,department,Base Salary,experience,bonus,age group,length,squared age,tax
0,Lina,25.0,0,IT,4500.0,3.0,450.0,Young,4,625.0,0.0
1,Omar,30.0,1,HR,5000.0,5.0,500.0,Old,4,900.0,0.0
2,Sami,NaN,1,Marketing,5200.0,2.0,520.0,Old,4,NaN,260.0
4,Rami,35.0,1,Finance,5600.0,6.0,560.0,Old,4,1225.0,280.0
5,Tariq,40.0,1,HR,6000.0,7.0,600.0,Old,5,1600.0,300.0
7,Zain,33.0,1,IT,5300.0,5.0,530.0,Old,4,1089.0,265.0

In [136]:
df['skills'] = [['Python', 'SQL'], ['Excel', 'PowerPoint'], ['Python', 'ML'],['DL', 'ML'],
    ['Python', 'SQL'], ['Excel', 'PowerPoint']]
print(df)
print('\n___________________after explode___________________________')
exploded_df = df.explode('skills')
print(exploded_df)

    name   age  gender department  Base Salary  experience  bonus age group  \
0   Lina  25.0       0         IT       4500.0         3.0  450.0     Young
1   Omar  30.0       1         HR       5000.0         5.0  500.0       Old
2   Sami   NaN       1  Marketing       5200.0         2.0  520.0       Old
4   Rami  35.0       1    Finance       5600.0         6.0  560.0       Old
5  Tariq  40.0       1         HR       6000.0         7.0  600.0       Old
7   Zain  33.0       1         IT       5300.0         5.0  530.0       Old

   length  squared age    tax               skills
0       4        625.0    0.0        [Python, SQL]
1       4        900.0    0.0  [Excel, PowerPoint]
2       4          NaN  260.0         [Python, ML]
4       4       1225.0  280.0             [DL, ML]
5       5       1600.0  300.0        [Python, SQL]
7       4       1089.0  265.0  [Excel, PowerPoint]

___________________after explode___________________________
    name   age  gender department  Base Salary  experience  bonus age group  \
0   Lina  25.0       0         IT       4500.0         3.0  450.0     Young
0   Lina  25.0       0         IT       4500.0         3.0  450.0     Young
1   Omar  30.0       1         HR       5000.0         5.0  500.0       Old
1   Omar  30.0       1         HR       5000.0         5.0  500.0       Old
2   Sami   NaN       1  Marketing       5200.0         2.0  520.0       Old
2   Sami   NaN       1  Marketing       5200.0         2.0  520.0       Old
4   Rami  35.0       1    Finance       5600.0         6.0  560.0       Old
4   Rami  35.0       1    Finance       5600.0         6.0  560.0       Old
5  Tariq  40.0       1         HR       6000.0         7.0  600.0       Old
5  Tariq  40.0       1         HR       6000.0         7.0  600.0       Old
7   Zain  33.0       1         IT       5300.0         5.0  530.0       Old
7   Zain  33.0       1         IT       5300.0         5.0  530.0       Old

   length  squared age    tax      skills
0       4        625.0    0.0      Python
0       4        625.0    0.0         SQL
1       4        900.0    0.0       Excel
1       4        900.0    0.0  PowerPoint
2       4          NaN  260.0      Python
2       4          NaN  260.0          ML
4       4       1225.0  280.0          DL
4       4       1225.0  280.0          ML
5       5       1600.0  300.0      Python
5       5       1600.0  300.0         SQL
7       4       1089.0  265.0       Excel
7       4       1089.0  265.0  PowerPoint

In [138]:
df.groupby('department').size().reset_index(name='EmployeeCount')

  department  EmployeeCount
0    Finance              1
1         HR              2
2         IT              2
3  Marketing              1

In [139]:
df.reindex(columns=['department','name','gender','age','Base Salary'])

  department   name  gender   age  Base Salary
0         IT   Lina       0  25.0       4500.0
1         HR   Omar       1  30.0       5000.0
2  Marketing   Sami       1   NaN       5200.0
4    Finance   Rami       1  35.0       5600.0
5         HR  Tariq       1  40.0       6000.0
7         IT   Zain       1  33.0       5300.0

In [140]:
df.set_index(['department','gender'])

,,name,age,Base Salary,experience,bonus,age group,length,squared age,tax,skills
department,gender,,,,,,,,,,
IT,0,Lina,25.0,4500.0,3.0,450.0,Young,4,625.0,0.0,"[Python, SQL]"
HR,1,Omar,30.0,5000.0,5.0,500.0,Old,4,900.0,0.0,"[Excel, PowerPoint]"
Marketing,1,Sami,NaN,5200.0,2.0,520.0,Old,4,NaN,260.0,"[Python, ML]"
Finance,1,Rami,35.0,5600.0,6.0,560.0,Old,4,1225.0,280.0,"[DL, ML]"
HR,1,Tariq,40.0,6000.0,7.0,600.0,Old,5,1600.0,300.0,"[Python, SQL]"
IT,1,Zain,33.0,5300.0,5.0,530.0,Old,4,1089.0,265.0,"[Excel, PowerPoint]"